# Generated by Django 2.1.7 on 2019-03-18 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('description', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('type', models.CharField(max_length=32)),
                ('pin', models.IntegerField()),
                ('data', models.CharField(max_length=128)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PiGPIO.Program')),
                ('successor_false', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_successor_false', to='PiGPIO.ProgramStep')),
                ('successor_true', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_successor_true', to='PiGPIO.ProgramStep')),
            ],
        ),
    ]
