# Generated by Django 2.1.7 on 2019-03-18 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PiGPIO', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programstep',
            name='position',
        ),
        migrations.AlterField(
            model_name='programstep',
            name='data',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='programstep',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='programstep',
            name='successor_false',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_successor_false', to='PiGPIO.ProgramStep'),
        ),
        migrations.AlterField(
            model_name='programstep',
            name='successor_true',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_successor_true', to='PiGPIO.ProgramStep'),
        ),
    ]
