# Generated by Django 2.1.7 on 2019-03-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PiGPIO', '0003_programstep_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programstep',
            name='successor_false',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='programstep',
            name='successor_true',
            field=models.IntegerField(null=True),
        ),
    ]
