# Generated by Django 2.1.7 on 2019-03-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PiGPIO', '0004_auto_20190322_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='running',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='programstep',
            name='data',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='programstep',
            name='num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
