# Generated by Django 2.1.7 on 2019-03-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PiGPIO', '0005_auto_20190326_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='logging',
            field=models.BooleanField(default=False),
        ),
    ]
