# Generated by Django 2.1.7 on 2019-03-25 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PiGPIO', '0006_program_logging'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(default='', max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PiGPIO.ProgramStep')),
            ],
        ),
    ]
