# Generated by Django 2.1.7 on 2019-04-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PiGPIO', '0009_auto_20190409_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programlog',
            name='step',
        ),
        migrations.RemoveField(
            model_name='programstep',
            name='program',
        ),
        migrations.RemoveField(
            model_name='program',
            name='logging',
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.DeleteModel(
            name='ProgramLog',
        ),
        migrations.DeleteModel(
            name='ProgramStep',
        ),
    ]
