# Generated by Django 2.1.7 on 2019-04-10 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PiGPIO', '0011_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('text', models.CharField(blank=True, default='', max_length=32)),
                ('color', models.CharField(default='#247896', max_length=8)),
                ('icon', models.CharField(blank=True, default='', max_length=32)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PiGPIO.Program')),
            ],
        ),
    ]
