# Generated by Django 2.1.7 on 2019-04-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PiGPIO', '0012_dashboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='color',
            new_name='background_color',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='font_color',
            field=models.CharField(default='#247896', max_length=8),
        ),
    ]
