# Generated by Django 2.1.7 on 2019-04-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PiGPIO', '0015_auto_20190410_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='font_color',
            field=models.CharField(default='#ffffff', max_length=8),
        ),
    ]
