# Generated by Django 2.1.7 on 2019-04-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PiGPIO', '0016_auto_20190411_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='tag',
            field=models.CharField(choices=[('INFO', 'INFO'), ('ERROR', 'ERROR'), ('LOG', 'LOG'), ('DEBUG', 'DEBUG')], default='INFO', max_length=32),
        ),
    ]
