# Generated by Django 2.1.7 on 2019-04-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PiGPIO', '0017_log_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='background_color',
            field=models.CharField(default='#247896', max_length=8, verbose_name='Hintergrund Farbe'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='col',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=1, max_length=1, verbose_name='Spalte'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='font_color',
            field=models.CharField(default='#ffffff', max_length=8, verbose_name='Text Farbe'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='row',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=1, max_length=1, verbose_name='Reihe'),
        ),
        migrations.AlterField(
            model_name='program',
            name='blockly_string',
            field=models.TextField(blank=True, default='', verbose_name='Blockly XML'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Beschreibung'),
        ),
    ]
